service:
  jwt:
    secret: ${SECRET_TOKEN}
    expiration: ${EXPIRATION_TOKEN}

spring:
  r2dbc:
    url: ${DATABASE_URL_MAIN}

  flyway:
    url: jdbc:postgresql://${FLYWAY_URL}
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    baseline-on-migrate: true
    validate-on-migrate: true