service:
  jwt:
    secret: ${SECRET_TOKEN}
    expiration: ${EXPIRATION_TOKEN}

spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  flyway:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    baseline-on-migrate: true
    validate-on-migrate: true