service:
  jwt:
    secret: fdskfjkdgjhdjfkdskf
    expiration: 60000

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:senha123@192.168.0.106:5432/doe

  flyway:
    url: jdbc:postgresql://192.168.0.106:5432/doe
    user: postgres
    password: senha123
    baseline-on-migrate: true
    validate-on-migrate: true