service:
  jwt:
    secret: ${SECRET_TOKEN}
    expiration: ${EXPIRATION_TOKEN}

amazon:
  s3:
    secret-key: ${S3_SECRET_KEY}
    access-key: ${S3_ACCESS_KEY}
    bucket-name: ${S3_BUCKET_NAME}

spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  flyway:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: ${PORT:5000}