CREATE TABLE CADASTRO_USUARIO (
	CODIGO serial NOT NULL,
	USUARIO varchar( 30 ) NOT NULL,
	SENHA varchar( 20 ) NOT NULL,
	NOME varchar( 50 ) NOT NULL,
	CONSTRAINT CADASTRO_USUARIO_PKEY PRIMARY KEY( CODIGO )
);