CREATE TABLE cadastro_endereco (
	CODIGO SERIAL NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	NUMERO VARCHAR(50),
	RUA_AVENIDA VARCHAR(50) NOT null,
	REGIAO VARCHAR (50),
	CODIGO_USUARIO INT NOT NULL,
	CONSTRAINT CADASTRO_ENDERECO_PKEY PRIMARY KEY( CODIGO ),
	CONSTRAINT FK_CADASTRO_USUARIO FOREIGN KEY( CODIGO_USUARIO ) REFERENCES CADASTRO_USUARIO( CODIGO ),
	CONSTRAINT CADASTRO_ENDERECO_CK_REGIAO CHECK ( REGIAO IN ('SUL', 'NORTE', 'LESTE', 'OESTE' ) )
);
