CREATE TABLE CADASTRO_DOACAO (
	CODIGO SERIAL NOT NULL,
	TIPO_DOACAO VARCHAR(70) NOT NULL,
	CODIGO_DOADOR INT NOT NULL,
	CODIGO_RECEBEDOR INT,
	DESCRICAO VARCHAR(100) NOT NULL,
	DATA_HORA_COLETA_DOADOR TIMESTAMP,
	DATA_HORA_ENTREGA_RECEBEDOR TIMESTAMP,
	STATUS_COLETA_DOADOR VARCHAR(10),
	STATUS_ENTREGA_RECEBEDOR VARCHAR(10),
	BUSCA_EM_CASA BOOLEAN NOT NULL,
	CONSTRAINT CADASTRO_DOACAO_PKEY PRIMARY KEY( CODIGO ),
	CONSTRAINT FK_DOADOR_CADASTRO_USUARIO FOREIGN KEY( CODIGO_DOADOR ) REFERENCES CADASTRO_USUARIO( CODIGO ),
	CONSTRAINT FK_RECEBEDOR_CADASTRO_USUARIO FOREIGN KEY( CODIGO_RECEBEDOR ) REFERENCES CADASTRO_USUARIO( CODIGO ),
	CONSTRAINT CK_STATUS_COLETA_DOADOR CHECK ( STATUS_COLETA_DOADOR IN ('PENDENTE', 'FINALIZADO') ),
	CONSTRAINT CK_STATUS_ENTREGA_RECEBEDOR CHECK ( STATUS_ENTREGA_RECEBEDOR IN ('PENDENTE', 'FINALIZADO') )
);