CREATE TABLE CADASTRO_DOACAO (
	CODIGO SERIAL NOT NULL,
	TIPO_DOACAO VARCHAR(70) NOT NULL,
	CODIGO_DOADOR INT NOT NULL,
	CODIGO_RECEBEDOR INT,
	DESCRICAO VARCHAR(100) NOT NULL,
	DATA_HORA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	STATUS VARCHAR(10),
	IS_ENTREGA BOOLEAN NOT NULL,
	CODIGO_ENDERECO_DOADOR INT,
	CODIGO_ENDERECO_RECEBEDOR INT,
	CONSTRAINT CADASTRO_DOACAO_PKEY PRIMARY KEY( CODIGO ),
	CONSTRAINT FK_DOADOR_CADASTRO_USUARIO FOREIGN KEY( CODIGO_DOADOR ) REFERENCES CADASTRO_USUARIO( CODIGO ),
	CONSTRAINT FK_RECEBEDOR_CADASTRO_USUARIO FOREIGN KEY( CODIGO_RECEBEDOR ) REFERENCES CADASTRO_USUARIO( CODIGO ),
	CONSTRAINT CK_STATUS CHECK ( STATUS IN ('PENDENTE', 'FINALIZADO') ),
	CONSTRAINT FK_CADASTRO_DOACAO_CODIGO_ENDERECO_DOADOR FOREIGN KEY( CODIGO_ENDERECO_DOADOR ) REFERENCES CADASTRO_ENDERECO( CODIGO ),
    CONSTRAINT FK_CADASTRO_DOACAO_CODIGO_ENDERECO_RECEBEDOR FOREIGN KEY( CODIGO_ENDERECO_RECEBEDOR ) REFERENCES CADASTRO_ENDERECO( CODIGO )
);