CREATE TABLE cadastro_endereco (
	CODIGO SERIAL NOT NULL,
	BAIRRO VARCHAR( 50 ) NOT NULL,
	CIDADE VARCHAR( 50 ) NOT NULL,
	ESTADO VARCHAR( 50 ) NOT NULL,
	NUMERO INT,
	RUA_AVENIDA VARCHAR( 50 ) NOT null,
	CODIGO_REGIAO INT NOT NULL,
	CODIGO_USUARIO INT NOT NULL,
	CONSTRAINT CADASTRO_ENDERECO_PKEY PRIMARY KEY( CODIGO ),
	CONSTRAINT FK_CADASTRO_USUARIO FOREIGN KEY( CODIGO_USUARIO ) REFERENCES CADASTRO_USUARIO( CODIGO )
);