CREATE TABLE PERFIL (
	CODIGO SERIAL NOT NULL,
	DESCRICAO VARCHAR(4) NOT NULL DEFAULT('CLIE'),
	CONSTRAINT PERFIL_PKEY PRIMARY KEY( CODIGO ),
	CONSTRAINT CK_PERFIL_DESCRICAO CHECK ( DESCRICAO IN ('CLIE', 'ADMI') )
);

INSERT INTO PERFIL (DESCRICAO) VALUES ('ADMI');
INSERT INTO PERFIL (DESCRICAO) VALUES ('CLIE');